[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.10.*"
dependencies = [
    "pandas>=2.3.0",
    "python-telegram-bot==20.3",
    "requests>=2.32.4"
]
